#!/bin/sh
export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/home/root:
USERAGENT="Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/109.0"
alias yget="/usr/bin/wget -T 15 -U \"$USERAGENT\" --header \"Cache-Control: no-cache\""
#. nvram_ops #for future use
NG() { nvram get "$1" ; }
trap ctrl_c SIGINT

# FreshTomato Upgrade Script -- HommeOursPorc 2024/04
# Last update == 2025-04-06
ver="v0.47"

help() {
echo -e "FreshTomato Upgrade Script $ver

Usage: ftup [options] [firmware path or URL]

Default is dirty upgrade (NVRAM untouched) unless '-c' or '-r' is specified.

Single option:
  --changelog      Print latest FreshTomato changelog.
  --check          Print latest FreshTomato version number.
  --erase-nvram    Erase all data in NVRAM memory (thorough).
  --id             Identify device.
  --list-firmware  Experimental: List available firmware.
                   Default: Latest version.
                   Optional: Specify version to list,
                   e.g. --list-firmware 2025.2

Options:
  -a               Experimental: Auto upgrade to the latest firmware.
  -c               Clean upgrade (no settings restoration).
  -d <path>        Overrides default download directory (/tmp/ftupwd/).
  -f               Force 'unzip on the fly' download mode.
                   This is for devices with low RAM that can't hold
                   both the zip and firmware files in RAM simultaneously).
  -g (ver./build)  Experimental: Get (download) chosen firmware.
                   Default (no args): Get latest version and same
                   build as the one currently running.
                   Optional: ver. (version), e.g. 2024.4
                   Optional: build, e.g. Mini, Max, VPN, AIO, etc. 
  -n               Use wget '--no-check-certificate'
                   (you can try this if wget fail to download the firmware).
  -o               Only download firmware (no installation).
  -r               Restore settings after upgrade (implies '-c'),
                   PlainText Backup script by @rs232 is required
                   which is available on the 'linksysinfo.org' forum.
  -y               Automatic 'YES' to prompts. USE WITH CAUTION!
  -z               Force zip download in tmpfs.

Infos:
 - Single option are meant to be run without any other arguments.
 - URL must begin with \"http(s)://\".
 - Supported format is zip, trx, bin and chk.
 - Experimental features can be inaccurate, use at your own risk.

WARNING:
   This script comes with no guarantee.
   This script, especially with option '-y', could be dangerous!
   Make sure you are using the right firmware before proceeding!
   
I'm NOT responsible for any bricked devices. Use at your own risks.
   
USE WITH CAUTION!\n"
}

error() {
# $1 = ERROR No
e=3
m="" # message
case $1 in
1)  m="Unknown argument.";;
2)  m="Too many arguments.";;
3)  m="Firmware path or URL is missing.";;
4)  m="No USB device found. Settings restoration is not possible.";;
5)  m="nvram_backup is missing. Settings restoration is not possible.";;
6)  m="Firmware format not supported.";;
7)  m="Out of memory, not enough RAM.";;
8)  m="Unable to download firmware.";;
9)  m="Firmware doesn't exist or file is empty.";;
10) m="ZIP archive is corrupted.";;
11) m="Can't unzip archive, it's either corrupted or not enough RAM.";;
12) m="ZIP archive countain zero or more than one firmware.";;
13) m="Upgrading firmware with JFFS enabled is not possible.";;
14) m="Backup is missing. Settings restoration is not possible.";;
15) e=5; m="Operation cancelled.";;
16) m="Can't fetch newest version number from freshtomato.org.";;
17) m="Destination directory doesn't exist.";;
18) m="Can't download zip file if source is not a zip file.";;
19) m="Can't download zip file if there's no file to download.";;
20) m="MD5 sum did NOT match! Impossible to verify downloaded firmware file integrity!";;
21) m="Firmware URL is missing.";;
22) m="Firmware informations doesn't match the router informations. Make sure you are using the right firmware for your device or try to upgrade without option '-y'.";;
23) m="Unable to fetch changelog data from GitHub.";;
24) m="Cannot use JFFS partition for upgrades. JFFS cannot get unmounted while still working from the '/jffs' directory.";;
25) m="Invalid version number. Version must be e.g. 2025.2";;
26) m="Invalid build type. Build must be e.g. Mini, Max, VPN, AIO, etc.";;
27) m="Unable to fetch firmware list.";;
28) m="No firmware match.";;
29) m="Router identification not accurate enough.";;
esac
ilog $e "$m"
kill $(jobs -p) &>/dev/null
rm -f ${WORKDIR}/*
exit $1
}

ilog() {
# $1 = logger Priority (logger -p)
# $2 = message to log
case $1 in
    7) e="DEBUG" ;;
    6) e="INFO" ;;
    5) e="NOTICE" ;;
    4) e="WARNING" ;;
    3) e="ERROR" ;;
esac
logger -p $1 -t $(basename "$0")[$$] "$2"
[ $1 -le 4 ] && echo -e "\n$e: $2\n" || echo "$2"
}

ctrl_c() {
kill $(jobs -p) &>/dev/null
echo; error 15
}

wait_loop() {
# $1 = wait time in seconds
# $2 = msg to print
c=$1
while [ $c -gt 0 ]; do
echo -ne "$2 $c\033[0K\r"
sleep 1
: $((c--))
done
}

id() {
MATCH=""
TARGETS="/tmp/targets_${CPU}.csv"
yget -q --no-check-certificate -O "$TARGETS" "https://github.com/HommeOursPorc/ftup/raw/refs/heads/main/targets_${CPU}.csv"
[ -s "$TARGETS" ] && {
    ACCURACY=25
    [ $(grep -wc "$FULLMODEL" "$TARGETS") -eq 1 ] && { ACCURACY=50 ; MATCH="$(grep -w "$FULLMODEL" "$TARGETS" | awk -F',' '{print $1}')" ; }
}
rm -f "$TARGETS"
echo "$FULLMODEL" | grep -qi "Cisco Linksys" && MAKE="Cisco Linksys" || MAKE="$(echo "$FULLMODEL" | awk '{print $1}')"
TMODEL="$(echo "$FULLMODEL" | awk '{if(NF>=3){{print $(NF-1)"_"$NF}}else{{print $NF}}}' | tr -d "/")"
FIX="$(NG t_fix1)"
ID="$(NG odmpid)"
[ "$FIX" == "$TMODEL" ] && MODEL="$FIX" || { [ "$ID" != "" ] && MODEL="$ID" || MODEL="$FIX" ; }
[ "$MATCH" != "" ] && { [ "$MATCH" == "$MODEL" ] && ACCURACY=100 || MODEL="$MATCH" ; }
SDK="$(echo "$OSVER" | awk '{ for(i=1; i<=NF; i++) { if(match($i, /^K+/)) { print $i; break; } } }')" # eg K26ARM
case "$SDK" in
    RTAC) SDKFULL="K26RT-AC";;
    RTN ) SDKFULL="K26RT-N";;
    RT  ) SDKFULL="K26";;
    *   ) SDKFULL="$SDK";;
esac
VAR="$(echo "$OSVER" | awk '{print $NF}')" # eg VPN-64K
[ "$CPU" == "mips" ] && {
    MIPSREV="$(echo "$SDK" | cut -d "_" -f1 | sed "s/K26//i")"
    SDK="$(echo "$SDK" | cut -d "_" -f2)"
    NVRAM="$(nvram show | grep "entries,.*bytes" | awk '{print ($3+$6)/1024}')K"
} || {
    NVRAM="$(nvram show 2>&1 >/dev/null | tr -d "()" | awk '{print ($2+$4)/1024}')K"
}
}

id_show() {
id
echo "
$FULLMODEL
FreshTomato $OSVER

       MAKE = $MAKE
      MODEL = $MODEL
        CPU = $([ "$MIPSREV" != "" ] && echo "$MIPSREV" || echo "ARM")
        SDK = $SDKFULL    $([ $USB -eq 1 ] && printf "\n        USB = YES")
      NVRAM = $NVRAM
      BUILD = $VAR
    VERSION = $CURVER

MODEL Accuracy = $(
    case "$ACCURACY" in
        100) echo "HIGH -- Matched online";;
         50) echo "MEDIUM -- Partial match";;
         25) echo "LOW -- No match (possible \"unnamed\" firmware)";;
          0) echo "POOR -- Best effort";;
    esac
)

Please report any incorrect results at
https://www.linksysinfo.org/index.php?threads/freshtomato-upgrade-script-v0-11.78326/
"
}

fw_list() {
# $1 == version/build
VER=""
BUILD=""
SED="\(BTgui-VPN\|BT-VPN\|BT\|Big-VPN\|Nocat-VPN\|Mega-VPN\|IPv6-VPN\|AIO_Lite\|AIO\|Custom\|MiniIPv6\|MiniVPN2\|MiniVPN\|Mini\|Max\|VPN\)"
GREP=$(echo $SED | tr -d "\\()" | tr "|" "\n")
URL="https://freshtomato.org/downloads/freshtomato-${CPU}"
NODE=""
TMPLIST="/tmp/tmplist.txt"
FWLIST="/tmp/fwlist.txt"
id
[ $ACCURACY -eq 0 ] && error 29
[ $ACCURACY -eq 25 ] && [ "$CPU" == "arm" -o "$SDK" == "RTAC" ] && error 29
[ $# -eq 1 ] && {
    [ $(echo "$1" | grep -c '/') -eq 1 ] && {
        VER="$(echo "$1" | awk -F'/' '{print $1}')"
        BUILD="$(echo "$1" | awk -F'/' '{print $2}')"
    } || {
        [ $(echo "$1" | grep -cE '20[0-9][0-9]\.[0-9]($|[0-9]$)') -eq 1 ] && VER="$1" || BUILD="$1"
    }
}
[ "$VER" == "" ] && VER="$(check_update | awk -F'=' '/Latest/ {print $2}' | tr -d ' ')"
[ $(echo "$VER" | grep -cE '20[0-9][0-9]\.[0-9]($|[0-9]$)') -ne 1 ] && error 25
YEAR="${VER%.*}"
[ $LIST -eq 1 ] && {
    BUILD="$(echo "$VAR" | sed "s/$SED/\.\+/i")"
} || {
    [ "$BUILD" == "" ] && {
        BUILD="$VAR"
    } || {
        [ $(printf "$GREP" | grep -cix "$BUILD") -eq 0 ] && error 26
        BUILD="$(echo "$VAR" | sed "s/$SED/$BUILD/i")"
    }
}
URL="${URL}/${YEAR}/${VER}"
[ "$CPU" == "arm" ] && {
    NODE="$(basename "$URL")"
} || {
    URL="${URL}/${SDKFULL}"
    NODE="$(basename "$URL")"
}
yget -q --no-check-certificate -O- "$URL" | grep "data-sort=" | sed "s/.*\(\/$NODE\/\)//g;s/\".*//g" | tr -d "/" | grep "^freshtomato" | awk -v var="$URL" '{print var"/"$0}' > "$TMPLIST"
[ "$SDK" == "RTN" ] && {
    URL="${URL}/Asus%20RT-Nxx%20%26%20CO"
    NODE="$(basename "$URL")"
    yget -q --no-check-certificate -O- "$URL" | grep "data-sort=" | sed "s/.*\(\/$NODE\/\)//g;s/\".*//g" | tr -d "/" | grep "^freshtomato" | awk -v var="$URL" '{print var"/"$0}' >> "$TMPLIST"
}
[ ! -s "$TMPLIST" ] && error 27
[ $ACCURACY -ge 50 ] && {
    # Named
    grep -qi "$MODEL" "$TMPLIST" || error 28
    grep -wi "$MODEL" "$TMPLIST" > "$FWLIST"
} || {
    # Unnamed
    PATTERN="^freshtomato-K26"
    SPECIAL=0
    if [ "$MIPSREV" == "MIPSR1" -a $USB -eq 0 ]; then
        PATTERN="${PATTERN}MIPSR1_$SDK-$VER"
    elif [ "$MIPSREV" == "MIPSR1" -a $USB -eq 1 ]; then
        PATTERN="${PATTERN}MIPSR1_$SDK-USB-$VER"
    elif [ $(echo "$BUILD" | grep -c "K$") -eq 1 ]; then
        PATTERN="${PATTERN}MIPSR2_$SDK-USB-$VER"
        SPECIAL=1
    elif [ "$MIPSREV" == "MIPSR2" -a $USB -eq 0 ]; then
        PATTERN="${PATTERN}MIPSR2_$SDK-NVRAM$NVRAM-$VER"
    elif [ "$MIPSREV" == "MIPSR2" -a $USB -eq 1 ]; then
        PATTERN="${PATTERN}MIPSR2_$SDK-USB-NVRAM$NVRAM-$VER"
    fi
    [ $SPECIAL -eq 0 ] && {
        grep "$PATTERN" "$TMPLIST" > "$FWLIST"
    } || {
        sed "s/\.zip//g" "$TMPLIST" | grep "K$" | grep "$PATTERN" > "$FWLIST"
    }
}
rm -f "$TMPLIST"
[ $(wc -l "$FWLIST" | awk '{print $1}') -eq 0 ] && error 28
# If --list-firmware then quit function
# List of firmware in /tmp/fwlist.txt
[ $LIST -eq 1 ] && return 0
# Else echo 1x firmware
[ $(grep -c "$BUILD" "$FWLIST") -eq 1 ] && grep "$BUILD" "$FWLIST" || error 28
}

fw_show() {
# $1 == version
LIST=1
FWLIST="/tmp/fwlist.txt"
[ $# -eq 1 ] && fw_list $1 || fw_list
cat "$FWLIST"
}

changelog() {
echo "Getting changelog from https://github.com/FreshTomato-Project ..."
yget -q --no-check-certificate -O /tmp/ftup_cl.txt "https://github.com/FreshTomato-Project/freshtomato-${CPU}/raw/refs/heads/${CPU}-master/CHANGELOG"
[ $? -ne 0 ] && error 23
echo -e "YOUR VERSION = $CURVER\nTO QUIT PRESS 'Q'\n\n$(cat /tmp/ftup_cl.txt)" | less
rm -f /tmp/ftup_cl.txt
}

check_update() {
LATESTVER="$(yget -q --no-check-certificate -O- "http://freshtomato.org/version.txt")"
[ "$LATESTVER" == "" ] && error 16
echo "Current version = $CURVER
Latest  version = $LATESTVER"
[ $(echo $LATESTVER | tr -d ".") -gt $(echo $CURVER | tr -d ".") ] && echo -e "UPDATE AVAILABLE!"
}

enough_memory() {
# $1 = FWSIZE
# enoughmem=0 --> no  (not enough)
# enoughmem=1 --> yes (proceed)
AVAIL=$(awk '/MemFree/ {print $2}' /proc/meminfo)
[ $1 -ge $AVAIL ] && echo 0 || echo 1
}

download() {
[ "$CPU" == "mips" ] && QUIET="-q" || QUIET=""
[ "$DLDIR" != "" ] && DESTDIR="$DLDIR" || DESTDIR="$WORKDIR"
[ "$(df -P "$DESTDIR" | tail -n1 | awk '{print $1}')" == "tmpfs" ] && TMPFS=1
yget -qS --spider $NOCHECK "$FWURL" 2>"${WORKDIR}/yget.out"
[ $? -eq 0 -a $(grep -ci "content-length" "${WORKDIR}/yget.out") -eq 1 ] && FWSIZE=$((($(awk 'tolower($0) ~ /content-length/ {print $2}' "${WORKDIR}/yget.out")/1024)*3))
rm -f "${WORKDIR}/yget.out"
[ $ISZIP -eq 1 -a $TMPFS -eq 1 -a $FORCEZIP -eq 0 -a $FORCEFLY -eq 0 -a $FWSIZE -gt 0 ] && [ $(enough_memory $FWSIZE) -eq 1 ] && FORCEZIP=1
echo "Starting download..."
{
c=0; until [ "$(pidof wget)" ];do c=$((c+1)); [ $c -le 21 ] && usleep 500000 || break ; done ; c=0
while [ "$(pidof wget)" ]; do
    c=$((c+1))
    sleep 1
    [ "$CPU" == "mips" -a $c -gt 1 ] && printf "Downloading... %02d:%02d:%02d\r" $((c/3600)) $(((c%3600)/60)) $((c%60))
done
printf "\rDownloaded in  %02d:%02d:%02d\n" $((c/3600)) $(((c%3600)/60)) $((c%60))
} &
[ $ISZIP -eq 1 -a $TMPFS -eq 1 -a $FORCEZIP -eq 0 ] || [ $FORCEFLY -eq 1 ] && {
    echo "Download mode: SLOW -- unzip on the fly"
    echo "Warning: This mode is very SLOW! Please be patient."
    rm -f "${WORKDIR}/pipe1" "${WORKDIR}/pipe2" ; mkfifo "${WORKDIR}/pipe1" "${WORKDIR}/pipe2"
    md5sum "${WORKDIR}/pipe1" > "${WORKDIR}/${filename}.md5" &
    unzip -l "${WORKDIR}/pipe2" > "${WORKDIR}/zip.list" &
    yget $QUIET $NOCHECK -O- "$FWURL" | tee "${WORKDIR}/pipe1" | tee "${WORKDIR}/pipe2" | unzip -o - "*.trx" "*.bin" "*.chk" -d "$DESTDIR" || error 8
    wait $(pidof wget) $(pidof unzip)
    [ $(grep -Ec "\.trx|\.bin|\.chk" "${WORKDIR}/zip.list") -eq 1 ] && fwname="$(awk '/\.trx|\.bin|\.chk/ {print $4}' "${WORKDIR}/zip.list")" || error 12
    DESTMD5SUM="$(awk '{print $1}' "${WORKDIR}/${filename}.md5")"
    ISZIP=0
    rm -f "${WORKDIR}/pipe1"  "${WORKDIR}/pipe2" "${WORKDIR}/${filename}.md5" "${WORKDIR}/zip.list"
    FWPATH="${DESTDIR}/$fwname"                                 
} || {
    echo "Download mode: FAST -- direct download"
    FWPATH="${DESTDIR}/$filename"
    yget $QUIET $NOCHECK -O "$FWPATH" "$FWURL" || error 8
    [ $OFFICIAL -eq 1 -a -s "$FWPATH" ] && DESTMD5SUM="$(md5sum "$FWPATH" | awk '{print $1}')"
}
sleep 1
[ ! -s "$FWPATH" ] && error 9
[ $OFFICIAL -eq 1 ] && {
    echo "Verifying MD5 SUM..."
    md5path="${FWURL%/*}/MD5SUM"
    SRCMD5SUM="$(yget -q $NOCHECK -O- "$md5path" | grep "$filename" | awk '{print $1}')"
    ERROR=0
    [ "$SRCMD5SUM" != "" ] && {
        echo "$SRCMD5SUM" > "${DESTDIR}/${filename}.md5"
        echo "Source   MD5 sum = $SRCMD5SUM"
        echo "Download MD5 sum = $DESTMD5SUM"
        [ "$SRCMD5SUM" == "$DESTMD5SUM" ] && echo -e "MD5 Match!\n" || ERROR=1
    } || {
        ERROR=1
    }
    [ $ERROR -eq 1 ] && { rm -f "$FWPATH" "${DESTDIR}/${filename}.md5" ; error 20 ; }
}
echo "saved: $FWPATH"
[ $ONLY -eq 1 ] && printf "Download completed.\n\n"
}

prep_file() {
[ "$FWPATH" == "" ] && {
    FWPATH="$FWURL"
    [ "$(df -P "$FWPATH" | tail -n1 | awk '{print $1}')" == "tmpfs" ] && TMPFS=1
}
[ $TMPFS -eq 0 -a $ISZIP -eq 0 ] && {
    cp -f "$FWPATH" "$WORKDIR" || error 7
    FWPATH="${WORKDIR}/${filename}"
}
[ $ISZIP -eq 1 ] && {
    unzip -t "$FWPATH" || error 10
    [ $(unzip -l "$FWPATH" | grep -Ec "\.trx|\.bin|\.chk") -eq 1 ] && fwname="$(unzip -l "$FWPATH" | grep -E "\.trx|\.bin|\.chk" | awk '{print $4}')" || error 12
    FWSIZE=$(($(unzip -l "$FWPATH" | grep -E "\.trx|\.bin|\.chk" | awk '{print $1}')/1024))
    [ $TMPFS -eq 1 ] && FWSIZE=$((${FWSIZE}+$(du "$FWPATH" | awk '{print $1}')))
    [ $(enough_memory $FWSIZE) -eq 0 ] && error 7
    unzip -o "$FWPATH" "$fwname" -d "$WORKDIR" || error 11
    [ $TMPFS -eq 1 ] && rm -f "$FWPATH"
    FWPATH="${WORKDIR}/$fwname"
    [ ! -s "$FWPATH" ] && error 9
}

# check if right firmware if possible
[ "$MODEL" == "" ] && id
WARN=""
fwname="$(basename "$FWPATH")"
[ "$CPU" == "arm" -a "$MODEL" != "R1D" ] && {
    [ "$(tail -n1 "$FWPATH" | strings | tail -n1)" != "$MODEL" ] && WARN="WARNING: Model name $MODEL NOT found inside the firmware file footer.\n"
}
[ $(echo "$fwname" | grep -c "$SDK") -ne 1 ] && WARN="${WARN}WARNING: Router SDK (${SDK}) doesn't match the one stated in the firmware name.\n"
nvsize="$(echo "$fwname" | grep -Eo "(|[1-9])[1-9][1-9]K")"
[ "$nvsize" != "$NVRAM" ] && WARN="${WARN}WARNING: NVRAM size (${NVRAM}) doesn't match with the size stated in the firmware name (${nvsize}).\n"
# check for mips r1 vs r2 ???
[ "$WARN" != "" ] && {
    printf "\n$WARN"
    [ $AUTOYES -eq 1 ] && error 22
    ilog 4 "Some information doesn't match, make sure you are using the right firmware before proceeding!!"
    printf "\nContinue anyway? $MSG"
    read ANSWER ; echo
    [ "$ANSWER" != "yes" ] && error 15
}
}

restore() {
printf "Creating backup..."
$NVBACKUP usbrestore all
[ -s "$AUTORUN" ] && printf " Done\n" || error 14
ilog 5 "Backup created successfully: $AUTORUN"
}

handle_jffs() {
JFFS=1
pwd | grep -q "^/jffs" && error 24
pwd -P | grep -q "^/jffs" && error 24
dirname "$0" | grep -q "^/jffs" && error 24
echo "$DLDIR" | grep -q "^/jffs" && error 24
echo "$FWURL" | grep -q "^/jffs" && error 24
echo "
WARNING: JFFS is enabled.
         Make sure you have a backup of its content as
         it is not guaranteed the content of JFFS
         will be preserved after a firmware upgrade."
[ $(NG jffs2_auto_unmount) -eq 1 ] && {
    printf "         Auto unmount JFFS during upgrade is enabled.\n\n"
    printf "JFFS will be stopped and unmounted\n"
    printf "\nTo cancel press CTRL+C\n\n"
    wait_loop 7 "Continuing in"
} || {
    [ $AUTOYES -eq 1 ] && {
        error 13
    } || {
        printf "\nUnmount JFFS to continue the upgrade?\n\n"
        printf "$MSG"
        read ANSWER ; echo
        [ "$ANSWER" != "yes" ] && error 15
    }
}
    kill_jffs() {
        kill -9 $(ps | grep -v "jffs.*gcd" | grep -v "ftup" | grep "[/]jffs" | awk '{print $1}') &>/dev/null
        which lsof &>/dev/null && {
            kill -9 $(lsof | grep -v "ftup" | grep "/jffs" | awk '{print $1}') &>/dev/null
        }
    }
printf "Stopping JFFS... "
sync && sleep 2
kill_jffs
service jffs stop &>/dev/null
sleep 1
c=0
while ps | grep -q "[j]ffs.*gcd"; do
    [ $c -eq 5 ] && { printf "Unable to unmount JFFS\n" ; error 13 ; }
    kill_jffs
    umount -fl /jffs &>/dev/null
    c=$(($c+1))
    sleep 1
done
lsmod | grep -q jffs && modprobe -r jffs jffs2 &>/dev/null
lsmod | grep -q jffs && { printf "Unable to unmount JFFS\n" ; error 13 ; }
printf "Done\n"
}

prepare_upgrade() {
# Prepare firmware flashing
sync
c=10; while [ "$(nvram get action_service)" -a $c -gt 0 ];do c=$((c-1));echo -ne "Please wait... $c\033[0K\r";sleep 1;done
nvram set action_service="upgrade-start"
sleep 2
kill -s SIGUSR1 1
c=60; while [ "$(nvram get action_service)" -a $c -gt 0 ];do c=$((c-1));echo -ne "Stopping services... $c\033[0K\r";sleep 1;done; printf "Stopping services... Done\n"
}

upgrade() {
# Write firmware file
ilog 6 "Writing firmware $fwname"
[ -e "${WORKDIR}/ftup.out" ] && rm -f ${WORKDIR}/ftup.out
[ "$CPU" == "arm" ] && {
    nohup mtd-write2 ${FWPATH} linux > ${WORKDIR}/ftup.out 2>/dev/null &
    MTD="mtd-write2"
} || {
    nohup mtd-write -w -i ${FWPATH} -d linux > ${WORKDIR}/ftup.out 2>/dev/null &
    MTD="mtd-write"
}
c=0; until [ "$(pidof "$MTD")" ];do c=$((c+1)); [ $c -le 21 ] && { echo -ne "Please wait... $c\033[0K\r"; usleep 500000; } || break ; done
c=0; while [ "$(pidof "$MTD")" ];do c=$((c+1)); echo -ne "Writing firmware... $c\033[0K\r";sleep 1;done; printf "Writing firmware... Done\n"
sleep 2

# Check if flash successful
[ ! -s "${WORKDIR}/ftup.out" ] && {
    ilog 3 "Writing of ${fwname} unsuccessful!!"
    FAIL=1
    [ $RESTORE -eq 1 ] && {
        NOMORE="restore.$(date '+%Y%m%d_%H%M%S')"
        mv -f "$AUTORUN" "$(dirname "$AUTORUN")/$NOMORE"
        ilog 6 "Auto settings restoration cancelled, restore.autorun was renamed $NOMORE"
    }
    echo -e "\nSomething went wrong. The router is NOT upgraded. The router will reboot.\n"
    echo -e "To cancel the reboot and retry the upgrade manually press 'Ctrl+C'\n"
    wait_loop 10 "Rebooting in"
    rboot
}
echo "mtd-write: $(cat ${WORKDIR}/ftup.out | sort -u)"
rm -f ${WORKDIR}/ftup.out
ilog 6 "Successfully flashed $fwname"
}

erase_nvram() {
ilog 6 "Erasing nvram"
[ "$CPU" == "arm" ] && mtd-erase2 nvram || mtd-erase -d nvram
sleep 2
}

rboot() {
[ $RESTORE -eq 1 -a $FAIL -eq 0 ] && ilog 6 "Your router will reboot twice to restore its settings. Please be patient."
sync
/sbin/reboot && kill -9 $PPID
exit
}


# Global Variables
WORKDIR="/tmp/ftupwd"
MSG="To continue type [yes], to cancel type [n]: "
OPTIONS=""
MODE=""
FAIL=0
REMOTE=0
OFFICIAL=0
FORCEZIP=0
FORCEFLY=0
DLDIR=""
SETDIR=0
NOCHECK=""
ONLY=0
ERASE=0
AUTOYES=0
RESTORE=0
NVBACKUP=""
AUTORUN=""
FWPATH=""
FWURL=""
FWSIZE=0
filename=""
extension=""
fwname=""
ISZIP=0
TMPFS=0
[ "$(uname -m)" == "mips" ] && CPU="mips" || CPU="arm"
MIPSREV=""
OSVER="$(NG os_version)"
CURVER="$(echo "$OSVER" | awk '{print $1}')" # eg 2023.3
FULLMODEL="$(NG t_model_name)"
MAKE=""
MODEL=""
ACCURACY=0
echo "$OSVER" | grep -qi usb && USB=1 || USB=0
SDK=""
SDKFULL=""
VAR=""
NVRAM=""
JFFS=0
LIST=0


# Check and set arguments
[ $# -eq 0 ] && { help; exit 0; }
[ $# -eq 1 ] && { [ "$1" == "help" -o "$1" == "-h" -o "$1" == "--help" ] && { help; exit 0; } }
[ $# -eq 1 ] && { printf "%s" "$1" | grep -q "^--" && {
    case $1 in
        --changelog)      changelog ; exit 0 ;;
        --check)          check_update ; exit 0 ;;
        --erase-nvram)    ERASE=1 ;;
        --id)             id_show ; exit 0 ;;
        --list-firmware)  fw_show ; exit 0 ;;
    esac
    }
}
[ $# -eq 2 -a "$1" == "--list-firmware" ] && { fw_show "$2" ; exit 0 ; }
[ $ERASE -eq 0 ] && {
for a in "$@"; do
    printf "%s" "$a" | grep -q "^-" && {
        a="$(printf "%s" "$a" | tr -d "-")"
        [ "$a" == "" ] && error 1
        OPTIONS="$(printf "%s" "$a" | grep -o . )"
        for o in $OPTIONS; do
            case $o in
                c) [ "$MODE"     == "" ] && MODE="clean" || error 2 ;;
                d) [ "$DLDIR"    == "" ] && { DLDIR=1 ; SETDIR=1 ; }         || error 2 ;;
                f) [ $FORCEFLY   -eq 0 ] && FORCEFLY=1   || error 2 ;;
                n) [ "$NOCHECK"  == "" ] && NOCHECK="--no-check-certificate" || error 2 ;;
                o) [ $ONLY       -eq 0 ] && ONLY=1       || error 2 ;;
                r) [ $RESTORE    -eq 0 ] && RESTORE=1    || error 2 ;;
                y) [ $AUTOYES    -eq 0 ] && AUTOYES=1    || error 2 ;;
                z) [ $FORCEZIP   -eq 0 ] && FORCEZIP=1   || error 2 ;;
                *) error 1 ;;
            esac
        done
    } || {
        [ $SETDIR -eq 1 ] && { [ -d "$a" ] && { DLDIR="$a" ; SETDIR=0 ; continue ; } || error 17 ; }
        [ "$FWURL" == "" ] && {
            printf "%s" "$a" | grep -qi "^http" && REMOTE=1
            printf "%s" "$a" | grep -Eqi "^http(|s)://(|www.)freshtomato.org" && OFFICIAL=1
            FWURL="$a"
        } || {
            error 2
        }
    }
done
}
[ $ERASE -eq 0 -a "$FWURL" == "" ] && error 3
[ "$FWURL" != "" ] && {
    filename="$(basename "$FWURL")"
    extension="${filename##*.}"
    [ "$extension" != "zip" -a "$extension" != "trx" -a "$extension" != "bin" -a "$extension" != "chk" ] && error 6
    [ "$extension" == "zip" ] && ISZIP=1
    [ $REMOTE -eq 0 ] && { [ ! -s "$FWURL" ] && error 9 ; }
}
[ "$DLDIR" != "" ] && { case "$DLDIR" in ./) DLDIR="." ;; ../) DLDIR=".." ;; esac ; }
[ "$DLDIR"   != "" -a $REMOTE -eq 0 ] && error 21
[ "$NOCHECK" != "" -a $REMOTE -eq 0 ] && error 21
[ $FORCEZIP -eq 1 -o $FORCEFLY -eq 1 ] && [ $REMOTE -eq 0 ] && error 19
[ $FORCEZIP -eq 1 -o $FORCEFLY -eq 1 ] && [ $REMOTE -eq 1 -a $ISZIP -eq 0 ] && error 18
[ ! -d "$WORKDIR" -a $ERASE  -eq 0 ] && mkdir "$WORKDIR"
[ $ONLY -eq 1 ] && { [ "$MODE" == "" -a $RESTORE -eq 0 -a $AUTOYES -eq 0 ] && { [ $REMOTE -eq 1 ] && { download ; exit 0 ; } || error 21 ; } || error 2 ; }
[ "$MODE"   == "" ] && { [ $RESTORE -eq 1 ] && MODE="clean" || MODE="dirty"; }
[ $RESTORE  -eq 1 ] && {
    [ $(mount | grep -q /mnt ; echo $?) -ne 0 ] && error 4
    NVBACKUP="$(which nvram_backup)"
    [ "$NVBACKUP" == "" ] && { [ -s "/tmp/nvram_backup" ] && NVBACKUP="/tmp/nvram_backup" || error 5 ; }
    AUTORUN="$(mount | grep /mnt | awk '{print $3}')/restore.autorun"
}


# Main
[ $ERASE -eq 1 ] && {
    printf "\n\n                POINT OF NO RETURN\n\n"
    printf "Erase all data in NVRAM memory (thorough)? $MSG"
    read ANSWER ; echo
    [ "$ANSWER" != "yes" ] && error 15
    { prepare_upgrade ; erase_nvram ; rboot ; } &
    wait
} || {
    [ $(NG jffs2_on) -eq 1 ] && handle_jffs
    [ $REMOTE -eq 1 ] && download
    prep_file
    printf "\n\n                POINT OF NO RETURN\n\n"
    printf "Make sure you are using the right firmware before proceeding!\n\n"
    printf "Current:\n"
    printf "   Router : $FULLMODEL\n"
    printf "   NVRAM  : $NVRAM\n"
    printf "   Version: $OSVER\n\n"
    printf "Upgrade with:\n"
    printf "   $fwname\n\n"
    [ $JFFS -eq 1 ] && printf "Warning: JFFS content might be lost, make sure to have backups!\n\n"
    [ "$MODE" == "clean" ] && printf "Warning: Clean upgrade mode selected.\nALL settings will be ERASED!\nClean upgrade is implied with option '-r'.\n\n"
    printf "Proceed $MODE upgrade?\n"
    [ $AUTOYES -eq 1 ] && {
        printf "\n\nTo cancel press CTRL+C\n\n"
        wait_loop 10 "Upgrade starting in"
    } || {
        printf "$MSG"
        read ANSWER ; echo
        [ "$ANSWER" != "yes" ] && error 15
    }
    ilog 6 "Starting $MODE upgrade with firmware '$fwname'"
    # starting upgrade in background to prevent disconnection incidents
    {
    [ $RESTORE -eq 1 ] && restore
    prepare_upgrade
    upgrade
    [ "$MODE" == "clean" ] && erase_nvram
    rboot
    } &
    wait
}
exit 0
